[package]
name = "core"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = { workspace = true }
tokio = { workspace = true }
reth-exex ={ workspace = true }
reth-primitives = { workspace = true }